
version: '2'

services:
   postgres:
      image: postgres:12
      
   pdm-backend:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      links:
         - "postgres:postgres"
      environment:
         - SECRET_KEY_BASE=${SECRET_KEY_BASE}